
name: cell-factory-design-course
dependencies:
        - python==3.6
        - ipykernel
        - pandas
        - matplotlib
        - ipywidgets
        - pip
        - pip:
          - plotly==2.0.12
          - cameo
          - escher>=1.6.0
